// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    Vtop___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    // Body
    bufp->chgBit(oldp+0,(vlSelfRef.clk));
    bufp->chgBit(oldp+1,(vlSelfRef.rst_));
    bufp->chgBit(oldp+2,(vlSelfRef.clk26m));
    bufp->chgBit(oldp+3,(vlSelfRef.rst26m_));
    bufp->chgBit(oldp+4,(vlSelfRef.s_apb_psel));
    bufp->chgBit(oldp+5,(vlSelfRef.s_apb_penable));
    bufp->chgBit(oldp+6,(vlSelfRef.s_apb_pwrite));
    bufp->chgIData(oldp+7,(vlSelfRef.s_apb_paddr),32);
    bufp->chgIData(oldp+8,(vlSelfRef.s_apb_pwdata),32);
    bufp->chgBit(oldp+9,(vlSelfRef.s_apb_pready));
    bufp->chgIData(oldp+10,(vlSelfRef.s_apb_prdata),32);
    bufp->chgBit(oldp+11,(vlSelfRef.s_apb_pslverr));
    bufp->chgBit(oldp+12,(vlSelfRef.rxd_i));
    bufp->chgBit(oldp+13,(vlSelfRef.txd_o));
    bufp->chgBit(oldp+14,(vlSelfRef.uart_int_o));
    bufp->chgBit(oldp+15,(vlSelfRef.cocotb_top__DOT__clk));
    bufp->chgBit(oldp+16,(vlSelfRef.cocotb_top__DOT__rst_));
    bufp->chgBit(oldp+17,(vlSelfRef.cocotb_top__DOT__clk26m));
    bufp->chgBit(oldp+18,(vlSelfRef.cocotb_top__DOT__rst26m_));
    bufp->chgBit(oldp+19,(vlSelfRef.cocotb_top__DOT__s_apb_psel));
    bufp->chgBit(oldp+20,(vlSelfRef.cocotb_top__DOT__s_apb_penable));
    bufp->chgBit(oldp+21,(vlSelfRef.cocotb_top__DOT__s_apb_pwrite));
    bufp->chgIData(oldp+22,(vlSelfRef.cocotb_top__DOT__s_apb_paddr),32);
    bufp->chgIData(oldp+23,(vlSelfRef.cocotb_top__DOT__s_apb_pwdata),32);
    bufp->chgBit(oldp+24,(vlSelfRef.cocotb_top__DOT__s_apb_pready));
    bufp->chgIData(oldp+25,(vlSelfRef.cocotb_top__DOT__s_apb_prdata),32);
    bufp->chgBit(oldp+26,(vlSelfRef.cocotb_top__DOT__s_apb_pslverr));
    bufp->chgBit(oldp+27,(vlSelfRef.cocotb_top__DOT__rxd_i));
    bufp->chgBit(oldp+28,(vlSelfRef.cocotb_top__DOT__txd_o));
    bufp->chgBit(oldp+29,(vlSelfRef.cocotb_top__DOT__uart_int_o));
    bufp->chgBit(oldp+30,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__clk));
    bufp->chgBit(oldp+31,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__clk26m));
    bufp->chgBit(oldp+32,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__rst_));
    bufp->chgBit(oldp+33,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__rst26m_));
    bufp->chgCData(oldp+34,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__paddr_i),4);
    bufp->chgIData(oldp+35,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__pwdata_i),32);
    bufp->chgBit(oldp+36,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__psel_i));
    bufp->chgBit(oldp+37,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__penable_i));
    bufp->chgBit(oldp+38,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__pwrite_i));
    bufp->chgBit(oldp+39,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__urxd_i));
    bufp->chgBit(oldp+40,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__pready_o));
    bufp->chgBit(oldp+41,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__utxd_o));
    bufp->chgBit(oldp+42,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__uart_int_o));
    bufp->chgIData(oldp+43,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__prdata_o),32);
    bufp->chgBit(oldp+44,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__rx_bpsclk));
    bufp->chgBit(oldp+45,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__st_check));
    bufp->chgBit(oldp+46,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__parity));
    bufp->chgBit(oldp+47,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__check));
    bufp->chgBit(oldp+48,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__p_error_ack));
    bufp->chgBit(oldp+49,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__st_error_ack));
    bufp->chgBit(oldp+50,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__rxrst));
    bufp->chgBit(oldp+51,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__rx_fifo_rinc));
    bufp->chgBit(oldp+52,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__rx_bpsen));
    bufp->chgBit(oldp+53,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__st_error));
    bufp->chgBit(oldp+54,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__p_error));
    bufp->chgBit(oldp+55,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__rx_fifo_rempty));
    bufp->chgCData(oldp+56,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__rx_fifo_cnt),5);
    bufp->chgCData(oldp+57,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__rdata_to_regif),8);
    bufp->chgBit(oldp+58,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__tx_bpsclk));
    bufp->chgBit(oldp+59,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__stop_bit));
    bufp->chgCData(oldp+60,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__data_to_tx),8);
    bufp->chgCData(oldp+61,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__two_tx_delay),4);
    bufp->chgBit(oldp+62,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__txrst));
    bufp->chgBit(oldp+63,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__tx_fifo_winc));
    bufp->chgBit(oldp+64,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__tx_bpsen));
    bufp->chgBit(oldp+65,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__tx_fifo_wfull));
    bufp->chgCData(oldp+66,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__tx_fifo_cnt),5);
    bufp->chgSData(oldp+67,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__baud_div),10);
    bufp->chgBit(oldp+68,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__clk26m));
    bufp->chgBit(oldp+69,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__rst26m_));
    bufp->chgBit(oldp+70,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__rx_bps_en));
    bufp->chgBit(oldp+71,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__tx_bps_en));
    bufp->chgSData(oldp+72,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__baud_div),10);
    bufp->chgBit(oldp+73,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__rx_bpsclk));
    bufp->chgBit(oldp+74,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__tx_bpsclk));
    bufp->chgSData(oldp+75,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__cnt_value),14);
    bufp->chgSData(oldp+76,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__cnt_baud_rx),14);
    bufp->chgSData(oldp+77,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__cnt_baud_tx),14);
    bufp->chgBit(oldp+78,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__clk));
    bufp->chgBit(oldp+79,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rst_));
    bufp->chgCData(oldp+80,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__paddr_i),4);
    bufp->chgIData(oldp+81,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__pwdata_i),32);
    bufp->chgBit(oldp+82,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__psel_i));
    bufp->chgBit(oldp+83,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__penable_i));
    bufp->chgBit(oldp+84,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__pwrite_i));
    bufp->chgBit(oldp+85,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_error));
    bufp->chgBit(oldp+86,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__p_error));
    bufp->chgBit(oldp+87,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rx_fifo_rempty));
    bufp->chgCData(oldp+88,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rx_fifo_cnt),5);
    bufp->chgCData(oldp+89,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rx_data),8);
    bufp->chgBit(oldp+90,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__tx_fifo_wfull));
    bufp->chgCData(oldp+91,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__tx_fifo_cnt),5);
    bufp->chgBit(oldp+92,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_int_o));
    bufp->chgIData(oldp+93,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__prdata_o),32);
    bufp->chgBit(oldp+94,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_check));
    bufp->chgBit(oldp+95,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__p_error_ack));
    bufp->chgBit(oldp+96,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_error_ack));
    bufp->chgBit(oldp+97,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rxrst));
    bufp->chgBit(oldp+98,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__stop_bit));
    bufp->chgCData(oldp+99,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__two_tx_delay),4);
    bufp->chgCData(oldp+100,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__tx_data),8);
    bufp->chgBit(oldp+101,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__txrst));
    bufp->chgBit(oldp+102,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__check));
    bufp->chgBit(oldp+103,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__parity));
    bufp->chgBit(oldp+104,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rx_fifo_rinc));
    bufp->chgBit(oldp+105,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__tx_fifo_winc));
    bufp->chgSData(oldp+106,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__baud_div),10);
    bufp->chgIData(oldp+107,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_tx),32);
    bufp->chgIData(oldp+108,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_rx),32);
    bufp->chgIData(oldp+109,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_baud),32);
    bufp->chgIData(oldp+110,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_conf),32);
    bufp->chgIData(oldp+111,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_rxtrig),32);
    bufp->chgIData(oldp+112,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_txtrig),32);
    bufp->chgIData(oldp+113,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_delay),32);
    bufp->chgIData(oldp+114,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_status),32);
    bufp->chgIData(oldp+115,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_rxfifo_stat),32);
    bufp->chgIData(oldp+116,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_txfifo_stat),32);
    bufp->chgBit(oldp+117,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__state));
    bufp->chgCData(oldp+118,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__state_en),2);
    bufp->chgBit(oldp+119,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rx_state));
    bufp->chgBit(oldp+120,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__tx_state));
    bufp->chgBit(oldp+121,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_status3_delay1));
    bufp->chgBit(oldp+122,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_status3_delay2));
    bufp->chgBit(oldp+123,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__neg_uart_status3));
    bufp->chgBit(oldp+124,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_status2_delay1));
    bufp->chgBit(oldp+125,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_status2_delay2));
    bufp->chgBit(oldp+126,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__neg_uart_status2));
    bufp->chgBit(oldp+127,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_error_syn1));
    bufp->chgBit(oldp+128,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_error_syn2));
    bufp->chgBit(oldp+129,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_error_syn3));
    bufp->chgBit(oldp+130,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_error_syn));
    bufp->chgBit(oldp+131,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__p_error_syn1));
    bufp->chgBit(oldp+132,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__p_error_syn2));
    bufp->chgBit(oldp+133,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__p_error_syn3));
    bufp->chgBit(oldp+134,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__p_error_syn));
    bufp->chgBit(oldp+135,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__wr_en));
    bufp->chgBit(oldp+136,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rd_en));
    bufp->chgBit(oldp+137,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__clk));
    bufp->chgBit(oldp+138,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rst_));
    bufp->chgBit(oldp+139,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__clk26m));
    bufp->chgBit(oldp+140,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rst26m_));
    bufp->chgBit(oldp+141,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__urxd_i));
    bufp->chgBit(oldp+142,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_bpsclk));
    bufp->chgBit(oldp+143,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_check));
    bufp->chgBit(oldp+144,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__parity));
    bufp->chgBit(oldp+145,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__check));
    bufp->chgBit(oldp+146,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__p_error_ack));
    bufp->chgBit(oldp+147,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_error_ack));
    bufp->chgBit(oldp+148,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rxrst));
    bufp->chgBit(oldp+149,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_fifo_rinc));
    bufp->chgBit(oldp+150,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_bpsen));
    bufp->chgBit(oldp+151,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_error));
    bufp->chgBit(oldp+152,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__p_error));
    bufp->chgBit(oldp+153,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_fifo_rempty));
    bufp->chgCData(oldp+154,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_fifo_cnt),5);
    bufp->chgCData(oldp+155,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__data_to_regif),8);
    bufp->chgBit(oldp+156,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_fifo_winc));
    bufp->chgCData(oldp+157,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__state),3);
    bufp->chgCData(oldp+158,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__nextstate),3);
    bufp->chgCData(oldp+159,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__wdata_state),2);
    bufp->chgCData(oldp+160,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__data_cnt),5);
    bufp->chgCData(oldp+161,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__data_rx),8);
    bufp->chgBit(oldp+162,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_fifo_wfull));
    bufp->chgBit(oldp+163,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__urxd_i_delay1));
    bufp->chgBit(oldp+164,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__urxd_i_delay2));
    bufp->chgBit(oldp+165,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__neg_urxd_i));
    bufp->chgBit(oldp+166,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_ack));
    bufp->chgBit(oldp+167,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_ack_delay1));
    bufp->chgBit(oldp+168,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_ack_delay2));
    bufp->chgBit(oldp+169,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_error_ack_delay1));
    bufp->chgBit(oldp+170,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_error_ack_delay2));
    bufp->chgBit(oldp+171,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__p_error_ack_delay1));
    bufp->chgBit(oldp+172,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__p_error_ack_delay2));
    bufp->chgBit(oldp+173,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_start));
    bufp->chgBit(oldp+174,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_start_delay1));
    bufp->chgBit(oldp+175,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_start_delay2));
    bufp->chgBit(oldp+176,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_check_syn1));
    bufp->chgBit(oldp+177,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_check_syn2));
    bufp->chgBit(oldp+178,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__parity_syn1));
    bufp->chgBit(oldp+179,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__parity_syn2));
    bufp->chgBit(oldp+180,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__check_syn1));
    bufp->chgBit(oldp+181,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__check_syn2));
    bufp->chgBit(oldp+182,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__start_right));
    bufp->chgBit(oldp+183,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__clk));
    bufp->chgBit(oldp+184,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__rst_));
    bufp->chgBit(oldp+185,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__clk26m));
    bufp->chgBit(oldp+186,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__rst26m_));
    bufp->chgBit(oldp+187,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_bpsclk));
    bufp->chgBit(oldp+188,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__check));
    bufp->chgBit(oldp+189,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__parity));
    bufp->chgBit(oldp+190,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__stop_bit));
    bufp->chgCData(oldp+191,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__uart_tx),8);
    bufp->chgCData(oldp+192,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__two_tx_delay),4);
    bufp->chgBit(oldp+193,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__txrst));
    bufp->chgBit(oldp+194,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_fifo_winc));
    bufp->chgBit(oldp+195,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_bpsen));
    bufp->chgBit(oldp+196,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__utxd_o));
    bufp->chgBit(oldp+197,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_fifo_wfull));
    bufp->chgCData(oldp+198,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_fifo_cnt),5);
    bufp->chgCData(oldp+199,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__state),3);
    bufp->chgCData(oldp+200,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__nextstate),3);
    bufp->chgCData(oldp+201,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__rdata_state),2);
    bufp->chgCData(oldp+202,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__data_cnt),4);
    bufp->chgCData(oldp+203,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__baud_cnt),4);
    bufp->chgBit(oldp+204,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_fifo_rinc));
    bufp->chgCData(oldp+205,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__data_tx),8);
    bufp->chgBit(oldp+206,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_fifo_rempty));
    bufp->chgBit(oldp+207,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_ack));
    bufp->chgBit(oldp+208,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_ack_delay1));
    bufp->chgBit(oldp+209,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_ack_delay2));
    bufp->chgBit(oldp+210,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_start));
    bufp->chgBit(oldp+211,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_start_delay1));
    bufp->chgBit(oldp+212,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_start_delay2));
    bufp->chgBit(oldp+213,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__stop_bit_syn1));
    bufp->chgBit(oldp+214,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__stop_bit_syn2));
    bufp->chgBit(oldp+215,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__check_syn1));
    bufp->chgBit(oldp+216,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__check_syn2));
    bufp->chgBit(oldp+217,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__parity_syn1));
    bufp->chgBit(oldp+218,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__parity_syn2));
    bufp->chgCData(oldp+219,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__two_tx_delay_syn1),4);
    bufp->chgCData(oldp+220,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__two_tx_delay_syn2),4);
    bufp->chgBit(oldp+221,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.clk));
    bufp->chgBit(oldp+222,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.rst_));
    bufp->chgBit(oldp+223,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.fifo_rst));
    bufp->chgBit(oldp+224,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.rinc));
    bufp->chgBit(oldp+225,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.winc));
    bufp->chgCData(oldp+226,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.data_i),8);
    bufp->chgBit(oldp+227,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.wfull));
    bufp->chgBit(oldp+228,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.rempty));
    bufp->chgCData(oldp+229,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.data_o),8);
    bufp->chgCData(oldp+230,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.fifo_cnt),5);
    bufp->chgCData(oldp+231,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.wptr),5);
    bufp->chgCData(oldp+232,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.rptr),5);
    bufp->chgCData(oldp+233,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[0]),8);
    bufp->chgCData(oldp+234,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[1]),8);
    bufp->chgCData(oldp+235,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[2]),8);
    bufp->chgCData(oldp+236,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[3]),8);
    bufp->chgCData(oldp+237,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[4]),8);
    bufp->chgCData(oldp+238,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[5]),8);
    bufp->chgCData(oldp+239,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[6]),8);
    bufp->chgCData(oldp+240,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[7]),8);
    bufp->chgCData(oldp+241,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[8]),8);
    bufp->chgCData(oldp+242,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[9]),8);
    bufp->chgCData(oldp+243,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[10]),8);
    bufp->chgCData(oldp+244,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[11]),8);
    bufp->chgCData(oldp+245,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[12]),8);
    bufp->chgCData(oldp+246,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[13]),8);
    bufp->chgCData(oldp+247,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[14]),8);
    bufp->chgCData(oldp+248,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[15]),8);
    bufp->chgBit(oldp+249,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.clk));
    bufp->chgBit(oldp+250,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.rst_));
    bufp->chgBit(oldp+251,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.fifo_rst));
    bufp->chgBit(oldp+252,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.rinc));
    bufp->chgBit(oldp+253,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.winc));
    bufp->chgCData(oldp+254,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.data_i),8);
    bufp->chgBit(oldp+255,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.wfull));
    bufp->chgBit(oldp+256,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.rempty));
    bufp->chgCData(oldp+257,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.data_o),8);
    bufp->chgCData(oldp+258,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.fifo_cnt),5);
    bufp->chgCData(oldp+259,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.wptr),5);
    bufp->chgCData(oldp+260,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.rptr),5);
    bufp->chgCData(oldp+261,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[0]),8);
    bufp->chgCData(oldp+262,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[1]),8);
    bufp->chgCData(oldp+263,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[2]),8);
    bufp->chgCData(oldp+264,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[3]),8);
    bufp->chgCData(oldp+265,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[4]),8);
    bufp->chgCData(oldp+266,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[5]),8);
    bufp->chgCData(oldp+267,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[6]),8);
    bufp->chgCData(oldp+268,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[7]),8);
    bufp->chgCData(oldp+269,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[8]),8);
    bufp->chgCData(oldp+270,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[9]),8);
    bufp->chgCData(oldp+271,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[10]),8);
    bufp->chgCData(oldp+272,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[11]),8);
    bufp->chgCData(oldp+273,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[12]),8);
    bufp->chgCData(oldp+274,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[13]),8);
    bufp->chgCData(oldp+275,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[14]),8);
    bufp->chgCData(oldp+276,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[15]),8);
}

void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_cleanup\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VlUnpacked<CData/*0:0*/, 1> __Vm_traceActivity;
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        __Vm_traceActivity[__Vi0] = 0;
    }
    // Body
    vlSymsp->__Vm_activity = false;
    __Vm_traceActivity[0U] = 0U;
}
