// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_cov.h"
class Vtop_uart_fifo;


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:
    // CELLS
    Vtop_uart_fifo* __PVT__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo;
    Vtop_uart_fifo* __PVT__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_,0,0);
        VL_IN8(clk26m,0,0);
        VL_IN8(rst26m_,0,0);
        VL_IN8(s_apb_psel,0,0);
        VL_IN8(s_apb_penable,0,0);
        VL_IN8(s_apb_pwrite,0,0);
        VL_OUT8(s_apb_pready,0,0);
        VL_OUT8(s_apb_pslverr,0,0);
        VL_IN8(rxd_i,0,0);
        VL_OUT8(txd_o,0,0);
        VL_OUT8(uart_int_o,0,0);
        CData/*0:0*/ cocotb_top__DOT__clk;
        CData/*0:0*/ cocotb_top__DOT__rst_;
        CData/*0:0*/ cocotb_top__DOT__clk26m;
        CData/*0:0*/ cocotb_top__DOT__rst26m_;
        CData/*0:0*/ cocotb_top__DOT__s_apb_psel;
        CData/*0:0*/ cocotb_top__DOT__s_apb_penable;
        CData/*0:0*/ cocotb_top__DOT__s_apb_pwrite;
        CData/*0:0*/ cocotb_top__DOT__s_apb_pready;
        CData/*0:0*/ cocotb_top__DOT__s_apb_pslverr;
        CData/*0:0*/ cocotb_top__DOT__rxd_i;
        CData/*0:0*/ cocotb_top__DOT__txd_o;
        CData/*0:0*/ cocotb_top__DOT__uart_int_o;
        CData/*0:0*/ cocotb_top__DOT____Vtogcov__clk;
        CData/*0:0*/ cocotb_top__DOT____Vtogcov__rst_;
        CData/*0:0*/ cocotb_top__DOT____Vtogcov__clk26m;
        CData/*0:0*/ cocotb_top__DOT____Vtogcov__rst26m_;
        CData/*0:0*/ cocotb_top__DOT____Vtogcov__s_apb_psel;
        CData/*0:0*/ cocotb_top__DOT____Vtogcov__s_apb_penable;
        CData/*0:0*/ cocotb_top__DOT____Vtogcov__s_apb_pwrite;
        CData/*0:0*/ cocotb_top__DOT____Vtogcov__s_apb_pready;
        CData/*0:0*/ cocotb_top__DOT____Vtogcov__s_apb_pslverr;
        CData/*0:0*/ cocotb_top__DOT____Vtogcov__rxd_i;
        CData/*0:0*/ cocotb_top__DOT____Vtogcov__txd_o;
        CData/*0:0*/ cocotb_top__DOT____Vtogcov__uart_int_o;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__clk;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__clk26m;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__rst_;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__rst26m_;
        CData/*3:0*/ cocotb_top__DOT__u_uart_top__DOT__paddr_i;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__psel_i;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__penable_i;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__pwrite_i;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__urxd_i;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__pready_o;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__utxd_o;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__uart_int_o;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__rx_bpsclk;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__st_check;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__parity;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__check;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__p_error_ack;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__st_error_ack;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__rxrst;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__rx_fifo_rinc;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__rx_bpsen;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__st_error;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__p_error;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__rx_fifo_rempty;
        CData/*4:0*/ cocotb_top__DOT__u_uart_top__DOT__rx_fifo_cnt;
        CData/*7:0*/ cocotb_top__DOT__u_uart_top__DOT__rdata_to_regif;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__tx_bpsclk;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__stop_bit;
    };
    struct {
        CData/*7:0*/ cocotb_top__DOT__u_uart_top__DOT__data_to_tx;
        CData/*3:0*/ cocotb_top__DOT__u_uart_top__DOT__two_tx_delay;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__txrst;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__tx_fifo_winc;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__tx_bpsen;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__tx_fifo_wfull;
        CData/*4:0*/ cocotb_top__DOT__u_uart_top__DOT__tx_fifo_cnt;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__pready_o;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__utxd_o;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__uart_int_o;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__rx_bpsclk;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__st_check;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__parity;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__check;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__p_error_ack;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__st_error_ack;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__rxrst;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__rx_fifo_rinc;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__rx_bpsen;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__st_error;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__p_error;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__rx_fifo_rempty;
        CData/*4:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__rx_fifo_cnt;
        CData/*7:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__rdata_to_regif;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__tx_bpsclk;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__stop_bit;
        CData/*7:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__data_to_tx;
        CData/*3:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__two_tx_delay;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__txrst;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__tx_fifo_winc;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__tx_bpsen;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__tx_fifo_wfull;
        CData/*4:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__tx_fifo_cnt;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__clk;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rst_;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__clk26m;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rst26m_;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__urxd_i;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_bpsclk;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_check;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__parity;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__check;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__p_error_ack;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_error_ack;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rxrst;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_fifo_rinc;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_bpsen;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_error;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__p_error;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_fifo_rempty;
        CData/*4:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_fifo_cnt;
        CData/*7:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__data_to_regif;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_fifo_winc;
        CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__state;
        CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__nextstate;
        CData/*1:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__wdata_state;
        CData/*4:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__data_cnt;
        CData/*7:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__data_rx;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_fifo_wfull;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__urxd_i_delay1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__urxd_i_delay2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__neg_urxd_i;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_ack;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_ack_delay1;
    };
    struct {
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_ack_delay2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_error_ack_delay1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_error_ack_delay2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__p_error_ack_delay1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__p_error_ack_delay2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_start;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_start_delay1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_start_delay2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_check_syn1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_check_syn2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__parity_syn1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__parity_syn2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__check_syn1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__check_syn2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__start_right;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__rx_bpsen;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__st_error;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__p_error;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__rx_fifo_rempty;
        CData/*4:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__rx_fifo_cnt;
        CData/*7:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__data_to_regif;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__rx_fifo_winc;
        CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__state;
        CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__nextstate;
        CData/*1:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__wdata_state;
        CData/*4:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__data_cnt;
        CData/*7:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__data_rx;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__rx_fifo_wfull;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__urxd_i_delay1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__urxd_i_delay2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__neg_urxd_i;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__rx_ack;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__rx_ack_delay1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__rx_ack_delay2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__st_error_ack_delay1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__st_error_ack_delay2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__p_error_ack_delay1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__p_error_ack_delay2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__rx_start;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__rx_start_delay1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__rx_start_delay2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__st_check_syn1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__st_check_syn2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__parity_syn1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__parity_syn2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__check_syn1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__check_syn2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT____Vtogcov__start_right;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__clk;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__rst_;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__clk26m;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__rst26m_;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_bpsclk;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__check;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__parity;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__stop_bit;
        CData/*7:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__uart_tx;
        CData/*3:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__two_tx_delay;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__txrst;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_fifo_winc;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_bpsen;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__utxd_o;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_fifo_wfull;
        CData/*4:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_fifo_cnt;
    };
    struct {
        CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__state;
        CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__nextstate;
        CData/*1:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__rdata_state;
        CData/*3:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__data_cnt;
        CData/*3:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__baud_cnt;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_fifo_rinc;
        CData/*7:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__data_tx;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_fifo_rempty;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_ack;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_ack_delay1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_ack_delay2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_start;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_start_delay1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_start_delay2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__stop_bit_syn1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__stop_bit_syn2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__check_syn1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__check_syn2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__parity_syn1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__parity_syn2;
        CData/*3:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__two_tx_delay_syn1;
        CData/*3:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__two_tx_delay_syn2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__tx_bpsen;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__utxd_o;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__tx_fifo_wfull;
        CData/*4:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__tx_fifo_cnt;
        CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__state;
        CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__nextstate;
        CData/*1:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__rdata_state;
        CData/*3:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__data_cnt;
        CData/*3:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__baud_cnt;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__tx_fifo_rinc;
        CData/*7:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__data_tx;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__tx_fifo_rempty;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__tx_ack;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__tx_ack_delay1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__tx_ack_delay2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__tx_start;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__tx_start_delay1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__tx_start_delay2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__stop_bit_syn1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__stop_bit_syn2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__check_syn1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__check_syn2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__parity_syn1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__parity_syn2;
        CData/*3:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__two_tx_delay_syn1;
        CData/*3:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT____Vtogcov__two_tx_delay_syn2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__clk26m;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__rst26m_;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__tx_bps_en;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__rx_bps_en;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__rx_bpsclk;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__tx_bpsclk;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT____Vtogcov__rx_bpsclk;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT____Vtogcov__tx_bpsclk;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__clk;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rst_;
        CData/*3:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__paddr_i;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__psel_i;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__penable_i;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__pwrite_i;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_error;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__p_error;
    };
    struct {
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rx_fifo_rempty;
        CData/*4:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rx_fifo_cnt;
        CData/*7:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rx_data;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__tx_fifo_wfull;
        CData/*4:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__tx_fifo_cnt;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_int_o;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_check;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__p_error_ack;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_error_ack;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rxrst;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__stop_bit;
        CData/*3:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__two_tx_delay;
        CData/*7:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__tx_data;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__txrst;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__check;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__parity;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rx_fifo_rinc;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__tx_fifo_winc;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__state;
        CData/*1:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__state_en;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rx_state;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__tx_state;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_status3_delay1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_status3_delay2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__neg_uart_status3;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_status2_delay1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_status2_delay2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__neg_uart_status2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_error_syn1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_error_syn2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_error_syn3;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_error_syn;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__p_error_syn1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__p_error_syn2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__p_error_syn3;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__p_error_syn;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__wr_en;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rd_en;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__uart_int_o;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__st_check;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__p_error_ack;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__st_error_ack;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__rxrst;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__stop_bit;
        CData/*3:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__two_tx_delay;
        CData/*7:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__tx_data;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__txrst;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__check;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__parity;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__rx_fifo_rinc;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__tx_fifo_winc;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__state;
        CData/*1:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__state_en;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__rx_state;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__tx_state;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__uart_status3_delay1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__uart_status3_delay2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__neg_uart_status3;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__uart_status2_delay1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__uart_status2_delay2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__neg_uart_status2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__st_error_syn1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__st_error_syn2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__st_error_syn3;
    };
    struct {
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__st_error_syn;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__p_error_syn1;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__p_error_syn2;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__p_error_syn3;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__p_error_syn;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__wr_en;
        CData/*0:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__rd_en;
        CData/*4:0*/ __Vdly__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__data_cnt;
        CData/*7:0*/ __Vdly__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__data_rx;
        CData/*3:0*/ __Vdly__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__baud_cnt;
        CData/*3:0*/ __Vdly__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__data_cnt;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk26m__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst26m___0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst___0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo__rst___0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo__rst___0;
        CData/*0:0*/ __VactContinue;
        SData/*9:0*/ cocotb_top__DOT__u_uart_top__DOT__baud_div;
        SData/*9:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__baud_div;
        SData/*9:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__baud_div;
        SData/*13:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__cnt_value;
        SData/*13:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__cnt_baud_rx;
        SData/*13:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__cnt_baud_tx;
        SData/*13:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT____Vtogcov__cnt_value;
        SData/*13:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT____Vtogcov__cnt_baud_rx;
        SData/*13:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT____Vtogcov__cnt_baud_tx;
        SData/*9:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__baud_div;
        SData/*9:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__baud_div;
        VL_IN(s_apb_paddr,31,0);
        VL_IN(s_apb_pwdata,31,0);
        VL_OUT(s_apb_prdata,31,0);
        IData/*31:0*/ cocotb_top__DOT__s_apb_paddr;
        IData/*31:0*/ cocotb_top__DOT__s_apb_pwdata;
        IData/*31:0*/ cocotb_top__DOT__s_apb_prdata;
        IData/*31:0*/ cocotb_top__DOT____Vtogcov__s_apb_paddr;
        IData/*31:0*/ cocotb_top__DOT____Vtogcov__s_apb_pwdata;
        IData/*31:0*/ cocotb_top__DOT____Vtogcov__s_apb_prdata;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__pwdata_i;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__prdata_o;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT____Vtogcov__prdata_o;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__pwdata_i;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__prdata_o;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_tx;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_rx;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_baud;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_conf;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_rxtrig;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_txtrig;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_delay;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_status;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_rxfifo_stat;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_txfifo_stat;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__prdata_o;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__uart_tx;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__uart_rx;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__uart_baud;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__uart_conf;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__uart_rxtrig;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__uart_txtrig;
    };
    struct {
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__uart_delay;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__uart_status;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__uart_rxfifo_stat;
        IData/*31:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT____Vtogcov__uart_txfifo_stat;
        IData/*31:0*/ __VactIterCount;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<8> __VactTriggered;
    VlTriggerVec<8> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__IDLE = 0U;
    static constexpr CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__START = 1U;
    static constexpr CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__RX_DATA = 3U;
    static constexpr CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__CHECK_DATA = 2U;
    static constexpr CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__STOP = 6U;
    static constexpr CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__SEND = 7U;
    static constexpr CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__IDLE = 0U;
    static constexpr CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__IRQ = 1U;
    static constexpr CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__START_BIT = 3U;
    static constexpr CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__TX_DATA = 2U;
    static constexpr CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__CHECK_BIT = 6U;
    static constexpr CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__STOP = 7U;
    static constexpr CData/*2:0*/ cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__DELAY = 5U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
    void __vlCoverInsert(uint32_t* countp, bool enable, const char* filenamep, int lineno, int column,
        const char* hierp, const char* pagep, const char* commentp, const char* linescovp);
};


#endif  // guard
