// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo__0(Vtop___024root* vlSelf, VerilatedVcd* tracep);
VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo__0(Vtop___024root* vlSelf, VerilatedVcd* tracep);

VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+1,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"rst_",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+3,0,"clk26m",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+4,0,"rst26m_",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+5,0,"s_apb_psel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+6,0,"s_apb_penable",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+7,0,"s_apb_pwrite",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+8,0,"s_apb_paddr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+9,0,"s_apb_pwdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+10,0,"s_apb_pready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+11,0,"s_apb_prdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+12,0,"s_apb_pslverr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+13,0,"rxd_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+14,0,"txd_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+15,0,"uart_int_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("cocotb_top", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+16,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+17,0,"rst_",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+18,0,"clk26m",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+19,0,"rst26m_",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+20,0,"s_apb_psel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+21,0,"s_apb_penable",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+22,0,"s_apb_pwrite",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+23,0,"s_apb_paddr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+24,0,"s_apb_pwdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+25,0,"s_apb_pready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+26,0,"s_apb_prdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+27,0,"s_apb_pslverr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+28,0,"rxd_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+29,0,"txd_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+30,0,"uart_int_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("u_uart_top", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+31,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+32,0,"clk26m",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+33,0,"rst_",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+34,0,"rst26m_",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+35,0,"paddr_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+36,0,"pwdata_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+37,0,"psel_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+38,0,"penable_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+39,0,"pwrite_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+40,0,"urxd_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+41,0,"pready_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+42,0,"utxd_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+43,0,"uart_int_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+44,0,"prdata_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+45,0,"rx_bpsclk",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+46,0,"st_check",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+47,0,"parity",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+48,0,"check",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+49,0,"p_error_ack",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+50,0,"st_error_ack",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+51,0,"rxrst",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+52,0,"rx_fifo_rinc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+53,0,"rx_bpsen",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+54,0,"st_error",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+55,0,"p_error",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+56,0,"rx_fifo_rempty",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+57,0,"rx_fifo_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+58,0,"rdata_to_regif",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+59,0,"tx_bpsclk",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+60,0,"stop_bit",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+61,0,"data_to_tx",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+62,0,"two_tx_delay",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+63,0,"txrst",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+64,0,"tx_fifo_winc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+65,0,"tx_bpsen",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+66,0,"tx_fifo_wfull",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+67,0,"tx_fifo_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+68,0,"baud_div",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->pushPrefix("u_uart_baud", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+69,0,"clk26m",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+70,0,"rst26m_",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+71,0,"rx_bps_en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+72,0,"tx_bps_en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+73,0,"baud_div",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBit(c+74,0,"rx_bpsclk",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+75,0,"tx_bpsclk",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+76,0,"cnt_value",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 13,0);
    tracep->declBus(c+77,0,"cnt_baud_rx",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 13,0);
    tracep->declBus(c+78,0,"cnt_baud_tx",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 13,0);
    tracep->popPrefix();
    tracep->pushPrefix("u_uart_reg_if", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+79,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+80,0,"rst_",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+81,0,"paddr_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+82,0,"pwdata_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+83,0,"psel_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+84,0,"penable_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+85,0,"pwrite_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+86,0,"st_error",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+87,0,"p_error",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+88,0,"rx_fifo_rempty",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+89,0,"rx_fifo_cnt",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+90,0,"rx_data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+91,0,"tx_fifo_wfull",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+92,0,"tx_fifo_cnt",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+93,0,"uart_int_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+94,0,"prdata_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+95,0,"st_check",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+96,0,"p_error_ack",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+97,0,"st_error_ack",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+98,0,"rxrst",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+99,0,"stop_bit",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+100,0,"two_tx_delay",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+101,0,"tx_data",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+102,0,"txrst",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+103,0,"check",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+104,0,"parity",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+105,0,"rx_fifo_rinc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+106,0,"tx_fifo_winc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+107,0,"baud_div",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+108,0,"uart_tx",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+109,0,"uart_rx",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+110,0,"uart_baud",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+111,0,"uart_conf",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+112,0,"uart_rxtrig",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+113,0,"uart_txtrig",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+114,0,"uart_delay",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+115,0,"uart_status",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+116,0,"uart_rxfifo_stat",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+117,0,"uart_txfifo_stat",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+118,0,"state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+119,0,"state_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+120,0,"rx_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+121,0,"tx_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+122,0,"uart_status3_delay1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+123,0,"uart_status3_delay2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+124,0,"neg_uart_status3",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+125,0,"uart_status2_delay1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+126,0,"uart_status2_delay2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+127,0,"neg_uart_status2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+128,0,"st_error_syn1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+129,0,"st_error_syn2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+130,0,"st_error_syn3",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+131,0,"st_error_syn",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+132,0,"p_error_syn1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+133,0,"p_error_syn2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+134,0,"p_error_syn3",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+135,0,"p_error_syn",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+136,0,"wr_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"rd_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("u_uart_rx", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+138,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+139,0,"rst_",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+140,0,"clk26m",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+141,0,"rst26m_",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+142,0,"urxd_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+143,0,"rx_bpsclk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+144,0,"st_check",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+145,0,"parity",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+146,0,"check",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+147,0,"p_error_ack",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+148,0,"st_error_ack",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+149,0,"rxrst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+150,0,"rx_fifo_rinc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+151,0,"rx_bpsen",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+152,0,"st_error",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+153,0,"p_error",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+154,0,"rx_fifo_rempty",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+155,0,"rx_fifo_cnt",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+156,0,"data_to_regif",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+157,0,"rx_fifo_winc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+158,0,"state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+159,0,"nextstate",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+160,0,"wdata_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+161,0,"data_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+162,0,"data_rx",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+163,0,"rx_fifo_wfull",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+164,0,"urxd_i_delay1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+165,0,"urxd_i_delay2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+166,0,"neg_urxd_i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+167,0,"rx_ack",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+168,0,"rx_ack_delay1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+169,0,"rx_ack_delay2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+170,0,"st_error_ack_delay1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+171,0,"st_error_ack_delay2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+172,0,"p_error_ack_delay1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+173,0,"p_error_ack_delay2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+174,0,"rx_start",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+175,0,"rx_start_delay1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+176,0,"rx_start_delay2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+177,0,"st_check_syn1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+178,0,"st_check_syn2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+179,0,"parity_syn1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+180,0,"parity_syn2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+181,0,"check_syn1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+182,0,"check_syn2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+183,0,"start_right",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+278,0,"IDLE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+279,0,"START",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+280,0,"RX_DATA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+281,0,"CHECK_DATA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+282,0,"STOP",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+283,0,"SEND",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->pushPrefix("u_uart_rxfifo", VerilatedTracePrefixType::SCOPE_MODULE);
    Vtop___024root__trace_init_sub__TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo__0(vlSelf, tracep);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("u_uart_tx", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+184,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+185,0,"rst_",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+186,0,"clk26m",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+187,0,"rst26m_",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+188,0,"tx_bpsclk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+189,0,"check",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+190,0,"parity",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+191,0,"stop_bit",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+192,0,"uart_tx",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+193,0,"two_tx_delay",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+194,0,"txrst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+195,0,"tx_fifo_winc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+196,0,"tx_bpsen",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+197,0,"utxd_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+198,0,"tx_fifo_wfull",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+199,0,"tx_fifo_cnt",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+200,0,"state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+201,0,"nextstate",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+202,0,"rdata_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+203,0,"data_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+204,0,"baud_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+205,0,"tx_fifo_rinc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+206,0,"data_tx",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+207,0,"tx_fifo_rempty",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+208,0,"tx_ack",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+209,0,"tx_ack_delay1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+210,0,"tx_ack_delay2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+211,0,"tx_start",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+212,0,"tx_start_delay1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+213,0,"tx_start_delay2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+214,0,"stop_bit_syn1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+215,0,"stop_bit_syn2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+216,0,"check_syn1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+217,0,"check_syn2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+218,0,"parity_syn1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+219,0,"parity_syn2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+220,0,"two_tx_delay_syn1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+221,0,"two_tx_delay_syn2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+278,0,"IDLE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+279,0,"IRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+280,0,"START_BIT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+281,0,"TX_DATA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+282,0,"CHECK_BIT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+283,0,"STOP",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+284,0,"DELAY",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->pushPrefix("u_uart_txfifo", VerilatedTracePrefixType::SCOPE_MODULE);
    Vtop___024root__trace_init_sub__TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo__0(vlSelf, tracep);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo__0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+222,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+223,0,"rst_",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+224,0,"fifo_rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+225,0,"rinc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+226,0,"winc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+227,0,"data_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+228,0,"wfull",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+229,0,"rempty",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+230,0,"data_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+231,0,"fifo_cnt",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+232,0,"wptr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+233,0,"rptr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->pushPrefix("ram", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 16; ++i) {
        tracep->declBus(c+234+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 7,0);
    }
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo__0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+250,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+251,0,"rst_",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+252,0,"fifo_rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+253,0,"rinc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+254,0,"winc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+255,0,"data_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+256,0,"wfull",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+257,0,"rempty",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+258,0,"data_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+259,0,"fifo_cnt",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+260,0,"wptr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+261,0,"rptr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->pushPrefix("ram", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 16; ++i) {
        tracep->declBus(c+262+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 7,0);
    }
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullCData(oldp+278,(0U),3);
    bufp->fullCData(oldp+279,(1U),3);
    bufp->fullCData(oldp+280,(3U),3);
    bufp->fullCData(oldp+281,(2U),3);
    bufp->fullCData(oldp+282,(6U),3);
    bufp->fullCData(oldp+283,(7U),3);
    bufp->fullCData(oldp+284,(5U),3);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelfRef.clk));
    bufp->fullBit(oldp+2,(vlSelfRef.rst_));
    bufp->fullBit(oldp+3,(vlSelfRef.clk26m));
    bufp->fullBit(oldp+4,(vlSelfRef.rst26m_));
    bufp->fullBit(oldp+5,(vlSelfRef.s_apb_psel));
    bufp->fullBit(oldp+6,(vlSelfRef.s_apb_penable));
    bufp->fullBit(oldp+7,(vlSelfRef.s_apb_pwrite));
    bufp->fullIData(oldp+8,(vlSelfRef.s_apb_paddr),32);
    bufp->fullIData(oldp+9,(vlSelfRef.s_apb_pwdata),32);
    bufp->fullBit(oldp+10,(vlSelfRef.s_apb_pready));
    bufp->fullIData(oldp+11,(vlSelfRef.s_apb_prdata),32);
    bufp->fullBit(oldp+12,(vlSelfRef.s_apb_pslverr));
    bufp->fullBit(oldp+13,(vlSelfRef.rxd_i));
    bufp->fullBit(oldp+14,(vlSelfRef.txd_o));
    bufp->fullBit(oldp+15,(vlSelfRef.uart_int_o));
    bufp->fullBit(oldp+16,(vlSelfRef.cocotb_top__DOT__clk));
    bufp->fullBit(oldp+17,(vlSelfRef.cocotb_top__DOT__rst_));
    bufp->fullBit(oldp+18,(vlSelfRef.cocotb_top__DOT__clk26m));
    bufp->fullBit(oldp+19,(vlSelfRef.cocotb_top__DOT__rst26m_));
    bufp->fullBit(oldp+20,(vlSelfRef.cocotb_top__DOT__s_apb_psel));
    bufp->fullBit(oldp+21,(vlSelfRef.cocotb_top__DOT__s_apb_penable));
    bufp->fullBit(oldp+22,(vlSelfRef.cocotb_top__DOT__s_apb_pwrite));
    bufp->fullIData(oldp+23,(vlSelfRef.cocotb_top__DOT__s_apb_paddr),32);
    bufp->fullIData(oldp+24,(vlSelfRef.cocotb_top__DOT__s_apb_pwdata),32);
    bufp->fullBit(oldp+25,(vlSelfRef.cocotb_top__DOT__s_apb_pready));
    bufp->fullIData(oldp+26,(vlSelfRef.cocotb_top__DOT__s_apb_prdata),32);
    bufp->fullBit(oldp+27,(vlSelfRef.cocotb_top__DOT__s_apb_pslverr));
    bufp->fullBit(oldp+28,(vlSelfRef.cocotb_top__DOT__rxd_i));
    bufp->fullBit(oldp+29,(vlSelfRef.cocotb_top__DOT__txd_o));
    bufp->fullBit(oldp+30,(vlSelfRef.cocotb_top__DOT__uart_int_o));
    bufp->fullBit(oldp+31,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__clk));
    bufp->fullBit(oldp+32,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__clk26m));
    bufp->fullBit(oldp+33,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__rst_));
    bufp->fullBit(oldp+34,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__rst26m_));
    bufp->fullCData(oldp+35,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__paddr_i),4);
    bufp->fullIData(oldp+36,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__pwdata_i),32);
    bufp->fullBit(oldp+37,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__psel_i));
    bufp->fullBit(oldp+38,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__penable_i));
    bufp->fullBit(oldp+39,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__pwrite_i));
    bufp->fullBit(oldp+40,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__urxd_i));
    bufp->fullBit(oldp+41,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__pready_o));
    bufp->fullBit(oldp+42,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__utxd_o));
    bufp->fullBit(oldp+43,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__uart_int_o));
    bufp->fullIData(oldp+44,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__prdata_o),32);
    bufp->fullBit(oldp+45,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__rx_bpsclk));
    bufp->fullBit(oldp+46,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__st_check));
    bufp->fullBit(oldp+47,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__parity));
    bufp->fullBit(oldp+48,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__check));
    bufp->fullBit(oldp+49,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__p_error_ack));
    bufp->fullBit(oldp+50,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__st_error_ack));
    bufp->fullBit(oldp+51,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__rxrst));
    bufp->fullBit(oldp+52,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__rx_fifo_rinc));
    bufp->fullBit(oldp+53,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__rx_bpsen));
    bufp->fullBit(oldp+54,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__st_error));
    bufp->fullBit(oldp+55,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__p_error));
    bufp->fullBit(oldp+56,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__rx_fifo_rempty));
    bufp->fullCData(oldp+57,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__rx_fifo_cnt),5);
    bufp->fullCData(oldp+58,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__rdata_to_regif),8);
    bufp->fullBit(oldp+59,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__tx_bpsclk));
    bufp->fullBit(oldp+60,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__stop_bit));
    bufp->fullCData(oldp+61,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__data_to_tx),8);
    bufp->fullCData(oldp+62,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__two_tx_delay),4);
    bufp->fullBit(oldp+63,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__txrst));
    bufp->fullBit(oldp+64,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__tx_fifo_winc));
    bufp->fullBit(oldp+65,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__tx_bpsen));
    bufp->fullBit(oldp+66,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__tx_fifo_wfull));
    bufp->fullCData(oldp+67,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__tx_fifo_cnt),5);
    bufp->fullSData(oldp+68,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__baud_div),10);
    bufp->fullBit(oldp+69,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__clk26m));
    bufp->fullBit(oldp+70,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__rst26m_));
    bufp->fullBit(oldp+71,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__rx_bps_en));
    bufp->fullBit(oldp+72,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__tx_bps_en));
    bufp->fullSData(oldp+73,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__baud_div),10);
    bufp->fullBit(oldp+74,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__rx_bpsclk));
    bufp->fullBit(oldp+75,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__tx_bpsclk));
    bufp->fullSData(oldp+76,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__cnt_value),14);
    bufp->fullSData(oldp+77,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__cnt_baud_rx),14);
    bufp->fullSData(oldp+78,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_baud__DOT__cnt_baud_tx),14);
    bufp->fullBit(oldp+79,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__clk));
    bufp->fullBit(oldp+80,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rst_));
    bufp->fullCData(oldp+81,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__paddr_i),4);
    bufp->fullIData(oldp+82,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__pwdata_i),32);
    bufp->fullBit(oldp+83,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__psel_i));
    bufp->fullBit(oldp+84,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__penable_i));
    bufp->fullBit(oldp+85,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__pwrite_i));
    bufp->fullBit(oldp+86,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_error));
    bufp->fullBit(oldp+87,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__p_error));
    bufp->fullBit(oldp+88,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rx_fifo_rempty));
    bufp->fullCData(oldp+89,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rx_fifo_cnt),5);
    bufp->fullCData(oldp+90,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rx_data),8);
    bufp->fullBit(oldp+91,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__tx_fifo_wfull));
    bufp->fullCData(oldp+92,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__tx_fifo_cnt),5);
    bufp->fullBit(oldp+93,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_int_o));
    bufp->fullIData(oldp+94,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__prdata_o),32);
    bufp->fullBit(oldp+95,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_check));
    bufp->fullBit(oldp+96,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__p_error_ack));
    bufp->fullBit(oldp+97,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_error_ack));
    bufp->fullBit(oldp+98,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rxrst));
    bufp->fullBit(oldp+99,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__stop_bit));
    bufp->fullCData(oldp+100,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__two_tx_delay),4);
    bufp->fullCData(oldp+101,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__tx_data),8);
    bufp->fullBit(oldp+102,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__txrst));
    bufp->fullBit(oldp+103,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__check));
    bufp->fullBit(oldp+104,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__parity));
    bufp->fullBit(oldp+105,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rx_fifo_rinc));
    bufp->fullBit(oldp+106,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__tx_fifo_winc));
    bufp->fullSData(oldp+107,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__baud_div),10);
    bufp->fullIData(oldp+108,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_tx),32);
    bufp->fullIData(oldp+109,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_rx),32);
    bufp->fullIData(oldp+110,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_baud),32);
    bufp->fullIData(oldp+111,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_conf),32);
    bufp->fullIData(oldp+112,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_rxtrig),32);
    bufp->fullIData(oldp+113,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_txtrig),32);
    bufp->fullIData(oldp+114,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_delay),32);
    bufp->fullIData(oldp+115,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_status),32);
    bufp->fullIData(oldp+116,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_rxfifo_stat),32);
    bufp->fullIData(oldp+117,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_txfifo_stat),32);
    bufp->fullBit(oldp+118,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__state));
    bufp->fullCData(oldp+119,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__state_en),2);
    bufp->fullBit(oldp+120,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rx_state));
    bufp->fullBit(oldp+121,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__tx_state));
    bufp->fullBit(oldp+122,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_status3_delay1));
    bufp->fullBit(oldp+123,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_status3_delay2));
    bufp->fullBit(oldp+124,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__neg_uart_status3));
    bufp->fullBit(oldp+125,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_status2_delay1));
    bufp->fullBit(oldp+126,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__uart_status2_delay2));
    bufp->fullBit(oldp+127,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__neg_uart_status2));
    bufp->fullBit(oldp+128,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_error_syn1));
    bufp->fullBit(oldp+129,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_error_syn2));
    bufp->fullBit(oldp+130,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_error_syn3));
    bufp->fullBit(oldp+131,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__st_error_syn));
    bufp->fullBit(oldp+132,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__p_error_syn1));
    bufp->fullBit(oldp+133,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__p_error_syn2));
    bufp->fullBit(oldp+134,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__p_error_syn3));
    bufp->fullBit(oldp+135,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__p_error_syn));
    bufp->fullBit(oldp+136,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__wr_en));
    bufp->fullBit(oldp+137,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_reg_if__DOT__rd_en));
    bufp->fullBit(oldp+138,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__clk));
    bufp->fullBit(oldp+139,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rst_));
    bufp->fullBit(oldp+140,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__clk26m));
    bufp->fullBit(oldp+141,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rst26m_));
    bufp->fullBit(oldp+142,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__urxd_i));
    bufp->fullBit(oldp+143,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_bpsclk));
    bufp->fullBit(oldp+144,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_check));
    bufp->fullBit(oldp+145,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__parity));
    bufp->fullBit(oldp+146,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__check));
    bufp->fullBit(oldp+147,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__p_error_ack));
    bufp->fullBit(oldp+148,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_error_ack));
    bufp->fullBit(oldp+149,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rxrst));
    bufp->fullBit(oldp+150,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_fifo_rinc));
    bufp->fullBit(oldp+151,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_bpsen));
    bufp->fullBit(oldp+152,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_error));
    bufp->fullBit(oldp+153,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__p_error));
    bufp->fullBit(oldp+154,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_fifo_rempty));
    bufp->fullCData(oldp+155,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_fifo_cnt),5);
    bufp->fullCData(oldp+156,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__data_to_regif),8);
    bufp->fullBit(oldp+157,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_fifo_winc));
    bufp->fullCData(oldp+158,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__state),3);
    bufp->fullCData(oldp+159,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__nextstate),3);
    bufp->fullCData(oldp+160,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__wdata_state),2);
    bufp->fullCData(oldp+161,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__data_cnt),5);
    bufp->fullCData(oldp+162,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__data_rx),8);
    bufp->fullBit(oldp+163,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_fifo_wfull));
    bufp->fullBit(oldp+164,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__urxd_i_delay1));
    bufp->fullBit(oldp+165,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__urxd_i_delay2));
    bufp->fullBit(oldp+166,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__neg_urxd_i));
    bufp->fullBit(oldp+167,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_ack));
    bufp->fullBit(oldp+168,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_ack_delay1));
    bufp->fullBit(oldp+169,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_ack_delay2));
    bufp->fullBit(oldp+170,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_error_ack_delay1));
    bufp->fullBit(oldp+171,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_error_ack_delay2));
    bufp->fullBit(oldp+172,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__p_error_ack_delay1));
    bufp->fullBit(oldp+173,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__p_error_ack_delay2));
    bufp->fullBit(oldp+174,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_start));
    bufp->fullBit(oldp+175,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_start_delay1));
    bufp->fullBit(oldp+176,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__rx_start_delay2));
    bufp->fullBit(oldp+177,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_check_syn1));
    bufp->fullBit(oldp+178,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__st_check_syn2));
    bufp->fullBit(oldp+179,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__parity_syn1));
    bufp->fullBit(oldp+180,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__parity_syn2));
    bufp->fullBit(oldp+181,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__check_syn1));
    bufp->fullBit(oldp+182,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__check_syn2));
    bufp->fullBit(oldp+183,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__start_right));
    bufp->fullBit(oldp+184,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__clk));
    bufp->fullBit(oldp+185,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__rst_));
    bufp->fullBit(oldp+186,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__clk26m));
    bufp->fullBit(oldp+187,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__rst26m_));
    bufp->fullBit(oldp+188,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_bpsclk));
    bufp->fullBit(oldp+189,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__check));
    bufp->fullBit(oldp+190,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__parity));
    bufp->fullBit(oldp+191,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__stop_bit));
    bufp->fullCData(oldp+192,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__uart_tx),8);
    bufp->fullCData(oldp+193,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__two_tx_delay),4);
    bufp->fullBit(oldp+194,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__txrst));
    bufp->fullBit(oldp+195,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_fifo_winc));
    bufp->fullBit(oldp+196,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_bpsen));
    bufp->fullBit(oldp+197,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__utxd_o));
    bufp->fullBit(oldp+198,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_fifo_wfull));
    bufp->fullCData(oldp+199,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_fifo_cnt),5);
    bufp->fullCData(oldp+200,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__state),3);
    bufp->fullCData(oldp+201,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__nextstate),3);
    bufp->fullCData(oldp+202,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__rdata_state),2);
    bufp->fullCData(oldp+203,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__data_cnt),4);
    bufp->fullCData(oldp+204,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__baud_cnt),4);
    bufp->fullBit(oldp+205,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_fifo_rinc));
    bufp->fullCData(oldp+206,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__data_tx),8);
    bufp->fullBit(oldp+207,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_fifo_rempty));
    bufp->fullBit(oldp+208,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_ack));
    bufp->fullBit(oldp+209,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_ack_delay1));
    bufp->fullBit(oldp+210,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_ack_delay2));
    bufp->fullBit(oldp+211,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_start));
    bufp->fullBit(oldp+212,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_start_delay1));
    bufp->fullBit(oldp+213,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__tx_start_delay2));
    bufp->fullBit(oldp+214,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__stop_bit_syn1));
    bufp->fullBit(oldp+215,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__stop_bit_syn2));
    bufp->fullBit(oldp+216,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__check_syn1));
    bufp->fullBit(oldp+217,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__check_syn2));
    bufp->fullBit(oldp+218,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__parity_syn1));
    bufp->fullBit(oldp+219,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__parity_syn2));
    bufp->fullCData(oldp+220,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__two_tx_delay_syn1),4);
    bufp->fullCData(oldp+221,(vlSelfRef.cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__two_tx_delay_syn2),4);
    bufp->fullBit(oldp+222,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.clk));
    bufp->fullBit(oldp+223,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.rst_));
    bufp->fullBit(oldp+224,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.fifo_rst));
    bufp->fullBit(oldp+225,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.rinc));
    bufp->fullBit(oldp+226,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.winc));
    bufp->fullCData(oldp+227,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.data_i),8);
    bufp->fullBit(oldp+228,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.wfull));
    bufp->fullBit(oldp+229,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.rempty));
    bufp->fullCData(oldp+230,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.data_o),8);
    bufp->fullCData(oldp+231,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.fifo_cnt),5);
    bufp->fullCData(oldp+232,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.wptr),5);
    bufp->fullCData(oldp+233,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.rptr),5);
    bufp->fullCData(oldp+234,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[0]),8);
    bufp->fullCData(oldp+235,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[1]),8);
    bufp->fullCData(oldp+236,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[2]),8);
    bufp->fullCData(oldp+237,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[3]),8);
    bufp->fullCData(oldp+238,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[4]),8);
    bufp->fullCData(oldp+239,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[5]),8);
    bufp->fullCData(oldp+240,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[6]),8);
    bufp->fullCData(oldp+241,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[7]),8);
    bufp->fullCData(oldp+242,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[8]),8);
    bufp->fullCData(oldp+243,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[9]),8);
    bufp->fullCData(oldp+244,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[10]),8);
    bufp->fullCData(oldp+245,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[11]),8);
    bufp->fullCData(oldp+246,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[12]),8);
    bufp->fullCData(oldp+247,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[13]),8);
    bufp->fullCData(oldp+248,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[14]),8);
    bufp->fullCData(oldp+249,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_rx__DOT__u_uart_rxfifo.ram[15]),8);
    bufp->fullBit(oldp+250,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.clk));
    bufp->fullBit(oldp+251,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.rst_));
    bufp->fullBit(oldp+252,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.fifo_rst));
    bufp->fullBit(oldp+253,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.rinc));
    bufp->fullBit(oldp+254,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.winc));
    bufp->fullCData(oldp+255,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.data_i),8);
    bufp->fullBit(oldp+256,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.wfull));
    bufp->fullBit(oldp+257,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.rempty));
    bufp->fullCData(oldp+258,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.data_o),8);
    bufp->fullCData(oldp+259,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.fifo_cnt),5);
    bufp->fullCData(oldp+260,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.wptr),5);
    bufp->fullCData(oldp+261,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.rptr),5);
    bufp->fullCData(oldp+262,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[0]),8);
    bufp->fullCData(oldp+263,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[1]),8);
    bufp->fullCData(oldp+264,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[2]),8);
    bufp->fullCData(oldp+265,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[3]),8);
    bufp->fullCData(oldp+266,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[4]),8);
    bufp->fullCData(oldp+267,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[5]),8);
    bufp->fullCData(oldp+268,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[6]),8);
    bufp->fullCData(oldp+269,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[7]),8);
    bufp->fullCData(oldp+270,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[8]),8);
    bufp->fullCData(oldp+271,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[9]),8);
    bufp->fullCData(oldp+272,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[10]),8);
    bufp->fullCData(oldp+273,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[11]),8);
    bufp->fullCData(oldp+274,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[12]),8);
    bufp->fullCData(oldp+275,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[13]),8);
    bufp->fullCData(oldp+276,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[14]),8);
    bufp->fullCData(oldp+277,(vlSymsp->TOP__cocotb_top__DOT__u_uart_top__DOT__u_uart_tx__DOT__u_uart_txfifo.ram[15]),8);
}
